export const TimelineEvents = {
  INTERVIEW_STARTED: "INTERVIEW_STARTED",
  AI_QUESTION: "AI_QUESTION",
  USER_STARTED_SPEAKING: "USER_STARTED_SPEAKING",
  USER_SUBMITTED_ANSWER: "USER_SUBMITTED_ANSWER",
  AI_EVALUATED: "AI_EVALUATED",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",

  FACE_LOST: "FACE_LOST",
  FACE_DETECTED: "FACE_DETECTED",

  LOOKING_AWAY: "LOOKING_AWAY",

  MULTIPLE_FACES: "MULTIPLE_FACES",

  INTEGRITY_WARNING: "INTEGRITY_WARNING",
} as const;
