export enum IntegrityEventType {
  FACE_LOST = "FACE_LOST",

  MULTIPLE_FACES = "MULTIPLE_FACES",

  LOOKING_AWAY = "LOOKING_AWAY",

  TAB_SWITCH = "TAB_SWITCH",

  WINDOW_BLUR = "WINDOW_BLUR",

  FULLSCREEN_EXIT = "FULLSCREEN_EXIT",

  CAMERA_OFF = "CAMERA_OFF",

  MIC_MUTED = "MIC_MUTED",

  SCREEN_SHARE_STOPPED = "SCREEN_SHARE_STOPPED",
}