export enum InterviewState {
  IDLE = "IDLE",

  GENERATING_QUESTION = "GENERATING_QUESTION",

  AI_SPEAKING = "AI_SPEAKING",

  LISTENING = "LISTENING",

  USER_SPEAKING = "USER_SPEAKING",

  PROCESSING_ANSWER = "PROCESSING_ANSWER",

  EVALUATING = "EVALUATING",

  COMPLETED = "COMPLETED",
}