export enum TimelineEventType {
  INTERVIEW_STARTED = "INTERVIEW_STARTED",

  QUESTION_ASKED = "QUESTION_ASKED",

  ANSWER_SUBMITTED = "ANSWER_SUBMITTED",

  LOOKING_AWAY = "LOOKING_AWAY",

  EYE_CONTACT_RECOVERED = "EYE_CONTACT_RECOVERED",

  FACE_LOST = "FACE_LOST",

  FACE_DETECTED = "FACE_DETECTED",

  INTEGRITY_WARNING = "INTEGRITY_WARNING",

  AI_SPEAKING = "AI_SPEAKING",

  USER_SPEAKING = "USER_SPEAKING",

  INTERVIEW_FINISHED = "INTERVIEW_FINISHED"
}